# Generated by Django 4.1.6 on 2023-02-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_alter_article_options_tag_scope_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='publish',
        ),
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tag'),
        ),
    ]
