# Generated by Django 4.1.6 on 2023-02-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
    ]
