# Generated by Django 4.1.6 on 2023-02-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_students_teachers_delete_student_delete_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
